
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: dwetteroth
  password: ltjmp6!
  timeout: 5000

development:
  <<: *default
  database: twitter-lite


test:
  <<: *default
  database: twitter-lite-test
